language: java
cache:
directories:
- $HOME/.m2
jdk:
- oraclejdk8
script:
- mvn clean package

sudo: required
services:
- docker
script:
- docker login -u 0626062 -p Dockerpw
- mvn clean package docker:build
